# Generated by Django 5.0.14 on 2026-09-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0009_galleryimage_thumbnail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tribute',
            index=models.Index(fields=['is_approved', '-created_at'], name='memorial_tr_is_appr_7749c6_idx'),
        ),
    ]
